language: python
python:
  - "3.4"

# command to install dependencies
install:
  - pip install coverage
  - pip install coveralls

# command to run tests
script: coverage run --omit="test/*" -m unittest

# publish results
after_success: coveralls